### ISSUE TITLE
seg fault jump / physic 

### ISSUE THREAD

**Issue by falaxx** [hsabouri/42_doom_nukem#24]
dans un coin dune piece avec portail, changer linclinaison du plafond + saut peut segfault. 

<img width="941" alt="Screen Shot 2019-06-05 at 2 44 09 PM" src="https://user-images.githubusercontent.com/42964999/58960815-341bbf80-87a8-11e9-99b2-e4646d767465.png">
<img width="791" alt="Screen Shot 2019-06-05 at 2 44 23 PM" src="https://user-images.githubusercontent.com/42964999/58960816-341bbf80-87a8-11e9-8986-1e0afd4c88a7.png">
<img width="1863" alt="Screen Shot 2019-06-05 at 2 37 08 PM" src="https://user-images.githubusercontent.com/42964999/58960768-223a1c80-87a8-11e9-8be6-c6696741ff1e.png">

**Comment by hsabouri** [comment]
J'arrive pas à le reproduire
